console.log('Improved hello girls!')
console.log(18-13)
console.log('How long until Retrograde is over', 18-13)
console.log('secret love message')
console.log('I am now a proper javascript file Ladies!')
console.log(2020-2018)
console.log(12)
